---
title: "Dairy Maps"
subtitle: "Visualizing dairy geography"
author: "Kota Minegishi"
date: "Updated: May 7, 2017"
output: 
  html_document:
    toc: true
    toc_depth: 1
    number_sections: true
---

<!-- <script src="target_blank.js"></script> -->

<!-- ```{r, results='asis'} -->
<!-- cat(' -->
<!-- <script> -->
<!--   d3.select("body").append("p").text("d3 made me") -->
<!-- </script> -->
<!-- ') -->
<!-- ``` -->

<!-- <script> -->
<!-- var links = document.querySelectorAll( 'a' ); -->
<!--     for( var i=0, limit=links.length; i<limit; i++ ) { -->
<!--         if(links[i].href.indexOf(location.hostname)===-1){ -->
<!--         links[i].setAttribute("target", "_blank"); -->
<!--       } -->
<!--     } -->
<!-- </script> -->


<!-- ```{r, echo = FALSE, results = 'asis'}  -->
<!-- library(shiny) -->
<!--   tags$head( -->
<!--     tags$script(type ="text/javascript",  src ="target_blank.js") -->
<!--   ) -->
<!-- ``` -->


The following are **interactive maps**. Be sure to click on a county or state to see the data.   

# Milk Cow Inventory 
Data Source: US Agricultural Census.

Milk cow inventory can be calculated from  [Agricultural Census summary files](http://www.icpsr.umich.edu/icpsrweb/ICPSR/studies/35206). We add up milk cows from the dairy farms with 20 or more cows. 

#### Levels {-}

<!-- * [2012](html/cow_inventory_2012.html)  -->

* <a href="html/cow_inventory_1992.html" target="_blank" >1992</a>,
<a href="html/cow_inventory_1997.html" target="_blank" >1997</a>,
<a href="html/cow_inventory_2002.html" target="_blank" >2002</a>,
<a href="html/cow_inventory_2007.html" target="_blank" >2007</a>,
<a href="html/cow_inventory_2012.html" target="_blank" >2012</a>

#### Changes {-}
* <a href="html/change_cow_inventory_2007_2012.html" target="_blank" >1992-1997</a>,
<a href="html/change_cow_inventory_2007_2012.html" target="_blank" >1997-2002</a>,
<a href="html/change_cow_inventory_2007_2012.html" target="_blank" >2002-2007</a>,
<a href="html/change_cow_inventory_2007_2012.html" target="_blank" >2007-2012</a>


Also, [USDA's 2012 Ag Census visualization page](https://www.agcensus.usda.gov/Publications/2012/Online_Resources/Ag_Census_Web_Maps/) has other map resources. 


# Dairy Employment
Data Source: Bureau of Labor Statistics

The Quarterly Census of Employment and Wages (QCEW) provides state and county level employment records (establishments, employees, and wages) by industry via North American Industry Classification System (NAICS). The QCEW is a byproduct of the state-level unemployment insurance (UI) administrative accounts. Since many small to medium dairy farms are not required to provide UI to their employees, the total employement in dairy farming is smaller than the actual. Nevertheless, it captures employment dynamics at a large scale. Currently, the QCEW is [publically available](https://data.bls.gov/cew/doc/access/csv_data_slices.htm)  from 2012 to a part of 2016. Information on NAICS is found [here](https://classcodes.com/naics-4-digit-industry-group-code-list/).  Also, due to [BLS's confidentiality rules](https://www.bls.gov/cew/cewfaq.htm#Q14), data for some counties cannot be disclosed to the public and hence are missing. Please note that with these shortcomings the following data are incomlete.     

#### Levels {-}

<!-- * Dairy farming (NAICS 112120): [county](html/employment_dairy_farming.html){:target="_blank"}, [state](html/employment_st_dairy_farming.html) -->

* Dairy farming (NAICS 112120): <a href="html/employment_dairy_farming.html" target="_blank">county</a>, 
<a href="html/employment_st_change_dairy_farming.html" target="_blank">state</a>

* Dairy food manufacturing (NAICS 3115): <a href="html/employment_dairy_food_mf.html" target="_blank">county</a>, 
<a href="html/employment_st_dairy_food_mf.html" target="_blank">state</a>

* Animal processing (NAICS 3116): <a href="html/employment_animal_processing.html" target="_blank">county</a>, 
<a href="html/employment_st_animal_processing.html" target="_blank">state</a>


#### Changes {-}

* Dairy farming (NAICS 112120): <a href="html/employment_change_dairy_farming.html" target="_blank">county</a>, 
<a href="html/employment_st_dairy_farming.html" target="_blank">state</a>

* Dairy food manufacturing (NAICS 3115): <a href="html/employment_change_dairy_food_mf.html" target="_blank">county</a>, 
<a href="html/employment_st_dairy_food_mf.html" target="_blank">state</a>

* Animal processing (NAICS 3116): <a href="html/employment_change_animal_processing.html" target="_blank">county</a>, 
<a href="html/employment_st_animal_processing.html" target="_blank">state</a>


# Grain Production
Data Source: US Agricultural Census.

#### Levels {-}

* Corn harvest: <a href="html/harvest_corn_1992.html" target="_blank" >1992</a>,
<a href="html/harvest_corn_1997.html" target="_blank" >1997</a>,
<a href="html/harvest_corn_2002.html" target="_blank" >2002</a>,
<a href="html/harvest_corn_2007.html" target="_blank" >2007</a>,
<a href="html/harvest_corn_2012.html" target="_blank" >2012</a>

* Soybean harvest: <a href="html/harvest_soybean_1992.html" target="_blank">1992</a>,
<a href="html/harvest_soybean_1997.html" target="_blank">1997</a>,
<a href="html/harvest_soybean_2002.html" target="_blank">2002</a>,
<a href="html/harvest_soybean_2007.html" target="_blank">2007</a>,
<a href="html/harvest_soybean_2012.html" target="_blank">2012</a>

#### Changes {-}

* Change in corn harvest: <a href="html/change_harvest_corn_1992_1997.html" target="_blank" >1992-1997</a>,
<a href="html/change_harvest_corn_1997_2002.html" target="_blank" >1997-2002</a>,
<a href="html/change_harvest_corn_2002_2007.html" target="_blank" >2002-2007</a>,
<a href="html/change_harvest_corn_2007_2012.html" target="_blank" >2007-2012</a>

* Change in soybean harvest: <a href="html/change_harvest_soybean_1992_1997.html" target="_blank" >1992-1997</a>,
<a href="html/change_harvest_soybean_1997_2002.html" target="_blank" >1997-2002</a>,
<a href="html/change_harvest_soybean_2002_2007.html" target="_blank" >2002-2007</a>,
<a href="html/change_harvest_soybean_2007_2012.html" target="_blank" >2007-2012</a>


# Rental Rates of Agricultural Land
Data Source: [National Agricultural Statistics Service](https://www.nass.usda.gov/Surveys/Guide_to_NASS_Surveys/Cash_Rents_by_County/)

Note: The data collection at the county level was not very comprehensive in early years. Since 2014, the data are biannually collected. 

#### Levels {-}

* Non-irrigated cropland: <a href="html/rent_non_irrigated_2008.html" target="_blank" >2008</a>,
<a href="html/rent_non_irrigated_2009.html" target="_blank" >2009</a>,
<a href="html/rent_non_irrigated_2010.html" target="_blank" >2010</a>,
<a href="html/rent_non_irrigated_2011.html" target="_blank" >2011</a>, 
<a href="html/rent_non_irrigated_2012.html" target="_blank" >2012</a>, 
<a href="html/rent_non_irrigated_2013.html" target="_blank" >2013</a>, 
<a href="html/rent_non_irrigated_2014.html" target="_blank" >2014</a>, 
<a href="html/rent_non_irrigated_2016.html" target="_blank" >2016</a>

* Irrigated cropland: <a href="html/rent_irrigated_2008.html" target="_blank" >2008</a>,
<a href="html/rent_irrigated_2009.html" target="_blank" >2009</a>,
<a href="html/rent_irrigated_2010.html" target="_blank" >2010</a>,
<a href="html/rent_irrigated_2011.html" target="_blank" >2011</a>, 
<a href="html/rent_irrigated_2012.html" target="_blank" >2012</a>, 
<a href="html/rent_irrigated_2013.html" target="_blank" >2013</a>, 
<a href="html/rent_irrigated_2014.html" target="_blank" >2014</a>, 
<a href="html/rent_irrigated_2016.html" target="_blank" >2016</a>

* Pastureland: <a href="html/rent_pastureland_2008.html" target="_blank" >2008</a>,
<a href="html/rent_pastureland_2009.html" target="_blank" >2009</a>,
<a href="html/rent_pastureland_2010.html" target="_blank" >2010</a>,
<a href="html/rent_pastureland_2011.html" target="_blank" >2011</a>, 
<a href="html/rent_pastureland_2012.html" target="_blank" >2012</a>, 
<a href="html/rent_pastureland_2013.html" target="_blank" >2013</a>, 
<a href="html/rent_pastureland_2014.html" target="_blank" >2014</a>, 
<a href="html/rent_pastureland_2016.html" target="_blank" >2016</a>


#### Changes {-}

* Non-irrigated cropland: <a href="html/change_rent_non_irrigated_2008.html" target="_blank" >2008</a>,
<a href="html/change_rent_non_irrigated_2009.html" target="_blank" >2009</a>,
<a href="html/change_rent_non_irrigated_2010.html" target="_blank" >2010</a>,
<a href="html/change_rent_non_irrigated_2011.html" target="_blank" >2011</a>, 
<a href="html/change_rent_non_irrigated_2012.html" target="_blank" >2012</a>, 
<a href="html/change_rent_non_irrigated_2013.html" target="_blank" >2013</a>, 
<a href="html/change_rent_non_irrigated_2014.html" target="_blank" >2014</a>, 
<a href="html/change_rent_non_irrigated_2016.html" target="_blank" >2016</a>

* Irrigated cropland: <a href="html/change_rent_irrigated_2008.html" target="_blank" >2008</a>,
<a href="html/change_rent_irrigated_2009.html" target="_blank" >2009</a>,
<a href="html/change_rent_irrigated_2010.html" target="_blank" >2010</a>,
<a href="html/change_rent_irrigated_2011.html" target="_blank" >2011</a>, 
<a href="html/change_rent_irrigated_2012.html" target="_blank" >2012</a>, 
<a href="html/change_rent_irrigated_2013.html" target="_blank" >2013</a>, 
<a href="html/change_rent_irrigated_2014.html" target="_blank" >2014</a>, 
<a href="html/change_rent_irrigated_2016.html" target="_blank" >2016</a>

* Pastureland: <a href="html/change_rent_pastureland_2008.html" target="_blank" >2008</a>,
<a href="html/change_rent_pastureland_2009.html" target="_blank" >2009</a>,
<a href="html/change_rent_pastureland_2010.html" target="_blank" >2010</a>,
<a href="html/change_rent_pastureland_2011.html" target="_blank" >2011</a>, 
<a href="html/change_rent_pastureland_2012.html" target="_blank" >2012</a>, 
<a href="html/change_rent_pastureland_2013.html" target="_blank" >2013</a>, 
<a href="html/change_rent_pastureland_2014.html" target="_blank" >2014</a>, 
<a href="html/change_rent_pastureland_2016.html" target="_blank" >2016</a>

For the evaluating land rental decisions, [Fair Rent](https://fairrent.umn.edu/Default.aspx) may be useful. 

# Hispanic Population
Data Source: [NIH National Cancer Institute](https://seer.cancer.gov/popdata/download.html)


#### Levels {-}

* Relative Hispanic population:  <a href="html/hispanic_pop_1990.html" target="_blank" >1990</a>,
<a href="html/hispanic_pop_1995.html" target="_blank" >1995</a>,
<a href="html/hispanic_pop_2000.html" target="_blank" >2000</a>,
<a href="html/hispanic_pop_2005.html" target="_blank" >2005</a>,
<a href="html/hispanic_pop_2010.html" target="_blank" >2010</a>,
<a href="html/hispanic_pop_2015.html" target="_blank" >2015</a>

#### Changes {-}

* Change in Hispanic population: <a href="html/change_hispanic_pop_1995.html" target="_blank" >1990-1995</a>,
<a href="html/change_hispanic_pop_2000.html" target="_blank" >1995-2000</a>,
<a href="html/change_hispanic_pop_2005.html" target="_blank" >2000-2005</a>,
<a href="html/change_hispanic_pop_2010.html" target="_blank" >2005-2010</a>,
<a href="html/change_hispanic_pop_2015.html" target="_blank" >2010-2015</a>




